- name: Add the user 'gotify' with a specific uid
  ansible.builtin.user:
    name: gotify
    uid: 1040
    shell: /usr/bin/nologin
    password: "*"
- apt:
   update_cache: yes
   upgrade: yes

- apt: 
    name:
      - python3-psycopg2
      - fail2ban
    state: present


- import_role:
    name: geerlingguy.postgresql
  vars:
    postgresql_python_library: python3-psycopg2
    postgresql_databases:
      - name: gotify
    postgresql_users:
      - name: gotify
    postgresql_hba_entries:
     - {type: local, database: all, user: all, auth_method: peer}
    postgresql_global_config_options:
     - option: listen_addresses
       value: ""

- import_tasks: gotify.yml
- import_tasks: backup.yml

- name: copy fail2ban filter
  copy:
    src: gotify.conf
    dest: /etc/fail2ban/filter.d/
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart fail2ban
- name: copy fail2ban conf
  copy:
    src: jail.local
    dest: /etc/fail2ban/
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart fail2ban



