
- name: systemd reload
  systemd:
    daemon_reload: true

- name: restart gotify
  service: name=gotify state=restarted enabled=yes
- name: restart fail2ban
  service: name=fail2ban state=restarted enabled=yes
